import type { Itinerary, Destination, Testimonial, TravelStory } from "./types";

export const WHATSAPP_NUMBER = "919930400694";
export const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER}?text=Hi!%20I%27m%20interested%20in%20planning%20a%20trip.`;
export const WHATSAPP_URL_PLAN = `https://wa.me/${WHATSAPP_NUMBER}?text=Hi!%20I%27d%20like%20to%20start%20planning%20a%20trip.`;
export const SUPPORT_EMAIL = "support@adventourist.in";
export const PHONE_DISPLAY = "+91 99304 00694";

export const DESTINATION_NAMES = [
  "Bali",
  "Leh Ladakh",
  "Thailand",
  "Sri Lanka",
  "Singapore",
  "Azerbaijan",
  "Vietnam",
  "Seychelles",
  "Himachal Pradesh",
  "Uttarakhand",
  "North East India",
];

export const MOCK_ITINERARIES: Itinerary[] = [
  {
    id: "1",
    slug: "bali-break-5-days-4-nights",
    title: "Bali Break",
    destination: "Bali",
    heroImage: "/site-images/bg-home-page.jpg",
    duration: 5,
    nights: 4,
    budgetFrom: 57000,
    tags: ["Beach", "Honeymoon", "Culture"],
    bestMonths: [4, 5, 6, 7, 8, 9],
    suitableFor: ["Couples", "Honeymooners"],
    travelStyle: ["Leisure", "Culture"],
    isPopular: true,
    badge: "Popular",
    status: "published",
    seoTitle: "Bali Break — 5 Days 4 Nights | Adventourist",
    seoDescription:
      "Experience the magic of Bali with our 5-day curated itinerary. Temples, rice terraces, beaches and spa — all taken care of.",
    overview:
      "Bali is more than a destination — it's a feeling. This 5-day itinerary takes you through the soul of the Island of the Gods: serene rice terraces at Tegallalang, the spiritual energy of Ubud, the surf culture of Seminyak, and the dramatic sea temple of Tanah Lot. Every day is crafted to balance adventure with rest, culture with indulgence.\n\nYou'll stay in a boutique villa with a private pool, eat at hidden warung restaurants the tourists don't know about, and have a local guide who grew up here share stories that no guidebook can replicate.\n\nThis is Bali the way it deserves to be experienced — not checked off a list, but felt.",
    highlights: [
      { icon: "🌾", label: "Tegallalang Rice Terraces", description: "Sunrise walk through UNESCO-heritage terraces" },
      { icon: "🛕", label: "Tanah Lot Temple", description: "Sea temple perched on a rocky outcrop at sunset" },
      { icon: "🧘", label: "Ubud Wellness", description: "Traditional Balinese massage and healing ritual" },
      { icon: "🏄", label: "Seminyak Beach", description: "Sunset cocktails and surf culture" },
      { icon: "🎨", label: "Art Village Celuk", description: "Silver smithing and local craft workshops" },
      { icon: "🍜", label: "Street Food Trail", description: "Midnight noodles and babi guling from a local" },
    ],
    days: [
      {
        day: 1, city: "Denpasar / Seminyak",
        activities: ["Airport pickup", "Check-in to boutique villa", "Sunset at Seminyak Beach", "Welcome dinner at Merah Putih"],
        stayType: "Boutique Hotel", stayName: "COMO Uma Seminyak",
      },
      {
        day: 2, city: "Ubud",
        activities: ["Tegallalang rice terraces at sunrise", "Tirta Empul holy spring temple", "Ubud art market", "Traditional Balinese cooking class"],
        stayType: "Boutique Hotel", stayName: "Komaneka at Bisma",
      },
      {
        day: 3, city: "Ubud / Kintamani",
        activities: ["Mount Batur sunrise trek", "Natural hot springs", "Coffee plantation tour", "Afternoon at leisure in Ubud"],
        stayType: "Boutique Hotel", stayName: "Komaneka at Bisma",
      },
      {
        day: 4, city: "Nusa Dua",
        activities: ["Transfer to Nusa Dua", "Tanah Lot temple at sunset", "Beach club evening", "Farewell seafood dinner"],
        stayType: "Resort", stayName: "St. Regis Bali",
      },
      {
        day: 5, city: "Denpasar",
        activities: ["Leisurely breakfast", "Last-minute shopping at Kuta", "Airport transfer and departure"],
        stayType: "Resort", stayName: "Checkout",
      },
    ],
    inclusions: [
      "4 nights accommodation (boutique villa/resort)",
      "Daily breakfast",
      "Airport transfers (pick-up and drop-off)",
      "All sightseeing as per itinerary",
      "English-speaking local guide",
      "Entrance fees to temples and attractions",
      "One traditional Balinese massage (60 min)",
    ],
    exclusions: [
      "International airfare",
      "Visa fees (Bali is visa-free for Indians)",
      "Meals not mentioned",
      "Personal expenses and shopping",
      "Travel insurance",
      "Tips for guides and drivers",
    ],
    faqs: [
      { question: "Is Bali visa-free for Indian passport holders?", answer: "Yes! Indians can visit Bali visa-free for up to 30 days under the Visa on Arrival (VOA) scheme. You pay USD 35 at the airport on arrival." },
      { question: "What's the best time to visit Bali?", answer: "April to October is ideal — dry season with minimal rain. The peak months are July and August. Shoulder season (April–May and September) offers the best balance of weather and fewer crowds." },
      { question: "Is this trip suitable for honeymooners?", answer: "Absolutely. We can customise the itinerary with private villa upgrades, romantic dinners, couples spa sessions, and surprise setups. Just let us know in your inquiry." },
      { question: "Can I customise this itinerary?", answer: "Yes — every itinerary we build is personalised. We can adjust the pace, add destinations like Nusa Penida or Lombok, upgrade stays, or modify activities based on your interests." },
    ],
    hotels: [
      { name: "COMO Uma Seminyak", image: "/bg-home-page.jpg", stars: 5, type: "Boutique Hotel" },
      { name: "Komaneka at Bisma", image: "/site-images/search-images-8.jpg", stars: 5, type: "Heritage Villa" },
      { name: "St. Regis Bali Resort", image: "/site-images/singapore.jpg", stars: 5, type: "Luxury Resort" },
    ],
  },
  {
    id: "2",
    slug: "singapore-malaysia-jewels-of-the-straits",
    title: "Jewels of the Straits",
    destination: "Singapore",
    heroImage: "/site-images/singapore.jpg",
    duration: 7,
    nights: 6,
    budgetFrom: 89000,
    tags: ["City", "Shopping", "Family"],
    bestMonths: [2, 3, 4, 10, 11],
    suitableFor: ["Families", "Couples", "Groups"],
    travelStyle: ["Leisure", "City"],
    status: "published",
    seoTitle: "Singapore & Malaysia — 7 Days 6 Nights | Adventourist",
    seoDescription: "Explore the best of Singapore and Malaysia in 7 days. Gardens by the Bay, Petronas Towers, Penang food trail — all in one trip.",
    overview: "Two cities, one trip. Singapore's futuristic skyline contrasts beautifully with Kuala Lumpur's Moorish grandeur and Penang's time-worn charm. This itinerary moves at a relaxed pace — enough time to wander night markets, find the best chilli crab, and still tick off the iconic sights.",
    highlights: [
      { icon: "🌿", label: "Gardens by the Bay", description: "Supertree Grove light show after dark" },
      { icon: "🗼", label: "Petronas Twin Towers", description: "Skybridge views at 170m above KL" },
      { icon: "🦁", label: "Sentosa Island", description: "Universal Studios and S.E.A. Aquarium" },
      { icon: "🍜", label: "Penang Food Trail", description: "Char kway teow and laksa from street hawkers" },
    ],
    days: [],
    inclusions: ["6 nights accommodation", "Daily breakfast", "Airport transfers", "City tours as per itinerary"],
    exclusions: ["Flights", "Visa fees", "Personal expenses", "Travel insurance"],
    faqs: [],
    hotels: [],
  },
  {
    id: "3",
    slug: "vietnam-ascending-dragon-6-days",
    title: "The Ascending Dragon — Vietnam",
    destination: "Vietnam",
    heroImage: "/site-images/malaysia.jpg",
    duration: 6,
    nights: 5,
    budgetFrom: 72000,
    tags: ["Culture", "Food", "Adventure"],
    bestMonths: [11, 12, 1, 2, 3],
    suitableFor: ["Solo", "Couples", "Friends"],
    travelStyle: ["Adventure", "Culture"],
    isNew: true,
    badge: "New",
    status: "published",
    seoTitle: "Vietnam Highlights — 6 Days 5 Nights | Adventourist",
    seoDescription: "Explore Hanoi's old quarter, cruise Ha Long Bay, and discover Hoi An's lantern streets on our curated Vietnam trip from Mumbai.",
    overview: "Vietnam rewards the curious traveller. From the frenetic energy of Hanoi's Old Quarter to the karst-studded waters of Ha Long Bay, and the tailor shops and lantern-lit streets of Hoi An — every day offers a new texture. Our 6-day route is designed so you experience the country's best without feeling rushed.",
    highlights: [
      { icon: "🚢", label: "Ha Long Bay Cruise", description: "Overnight luxury junk boat through 1,600 limestone islands" },
      { icon: "🏮", label: "Hoi An Ancient Town", description: "UNESCO heritage old town, lantern festivals, tailor shops" },
      { icon: "🍜", label: "Hanoi Street Food", description: "Bun cha, pho and banh mi from legendary street vendors" },
      { icon: "🛵", label: "Motorbike Night Tour", description: "See Hanoi like a local on the back of a xe om" },
    ],
    days: [],
    inclusions: ["5 nights accommodation", "Ha Long Bay cruise (1 night)", "Daily breakfast", "Airport transfers"],
    exclusions: ["Flights", "Visa on arrival fee (~USD 25)", "Personal expenses"],
    faqs: [],
    hotels: [],
  },
  {
    id: "4",
    slug: "leh-ladakh-odyssey-8-days",
    title: "Leh Ladakh Odyssey",
    destination: "Leh Ladakh",
    heroImage: "/site-images/search-images-8.jpg",
    duration: 8,
    nights: 7,
    budgetFrom: 45000,
    tags: ["Mountains", "Adventure", "Solo"],
    bestMonths: [6, 7, 8, 9],
    suitableFor: ["Solo", "Couples", "Adventure Seekers"],
    travelStyle: ["Adventure", "Offbeat"],
    isPopular: true,
    badge: "Bestseller",
    status: "published",
    seoTitle: "Leh Ladakh Odyssey — 8 Days | Adventourist",
    seoDescription: "Experience the raw beauty of Leh Ladakh — Pangong Lake, Nubra Valley, ancient monasteries and the world's highest motorable roads.",
    overview: "Ladakh is not just a destination — it's a state of mind. At 11,000 feet, where the air is thin and the sky is impossibly blue, something shifts. This 8-day itinerary takes you through the essential Ladakh: the lunar landscape of Nubra Valley, the electric-blue mirror of Pangong Lake, the ancient monasteries of Hemis and Thiksey, and the electric mountain passes that leave you breathless — literally and figuratively.",
    highlights: [
      { icon: "🏔️", label: "Pangong Tso Lake", description: "The famous blue lake from 3 Idiots, 14,270 ft elevation" },
      { icon: "🐪", label: "Nubra Valley", description: "Double-humped Bactrian camels and sand dunes at 10,000 ft" },
      { icon: "🛕", label: "Hemis Monastery", description: "Ladakh's largest monastery, home to the Hemis Festival" },
      { icon: "🚗", label: "Khardung La Pass", description: "World's highest motorable road at 18,380 feet" },
    ],
    days: [],
    inclusions: ["7 nights accommodation (hotels + camps)", "All meals in remote areas", "Inner Line Permits", "Airport transfers", "SUV transport throughout"],
    exclusions: ["Flights to/from Leh", "Personal expenses", "Travel insurance (mandatory)", "Tips"],
    faqs: [
      { question: "Do I need any permits for Ladakh?", answer: "Yes. Indian nationals need an Inner Line Permit (ILP) to visit restricted areas like Nubra Valley, Pangong Lake, and Tso Moriri. We arrange all permits as part of the trip." },
      { question: "What about altitude sickness?", answer: "Leh is at 11,500 ft. We build in an acclimatisation day on Day 1 — no strenuous activity, lots of water, and early sleep. Most travellers adapt fine with this protocol. We recommend consulting your doctor before travel if you have any cardiac conditions." },
    ],
    hotels: [],
  },
  {
    id: "5",
    slug: "seychelles-island-paradise-7-days",
    title: "Seychelles: Island Paradise",
    destination: "Seychelles",
    heroImage: "/site-images/dubai.jpg",
    duration: 7,
    nights: 6,
    budgetFrom: 120000,
    tags: ["Luxury", "Honeymoon", "Beach"],
    bestMonths: [4, 5, 10, 11],
    suitableFor: ["Honeymooners", "Couples"],
    travelStyle: ["Luxury", "Leisure"],
    badge: "Premium",
    status: "published",
    seoTitle: "Seychelles Island Paradise — 7 Days | Adventourist",
    seoDescription: "The ultimate luxury honeymoon in Seychelles. Pristine beaches, coral reefs, and private overwater villas — all arranged by Adventourist.",
    overview: "Seychelles is the definition of paradise. 115 islands scattered across the Indian Ocean, each with granite boulders, powder-white sand, and water so clear you can see the coral from the surface. This 7-day itinerary covers the three main islands — Mahé, Praslin, and La Digue — giving you the full Seychelles experience.",
    highlights: [
      { icon: "🏖️", label: "Anse Lazio Beach", description: "Consistently ranked among the world's top 5 beaches" },
      { icon: "🐢", label: "Aldabra Giant Tortoises", description: "Walk among 150-year-old tortoises in their natural habitat" },
      { icon: "🤿", label: "Coral Reef Snorkelling", description: "Pristine Marine National Park with sea turtles and manta rays" },
      { icon: "🚲", label: "La Digue by Bicycle", description: "No cars allowed — the island is explored only on two wheels" },
    ],
    days: [],
    inclusions: ["6 nights luxury accommodation", "Island hopping ferry transfers", "Daily breakfast", "Snorkelling excursion", "Nature Reserve entry"],
    exclusions: ["International flights", "Seychelles Tourism Tax (~USD 40)", "Scuba diving", "Spa treatments", "Personal expenses"],
    faqs: [],
    hotels: [],
  },
  {
    id: "6",
    slug: "thailand-highlights-6-days",
    title: "Thailand Highlights",
    destination: "Thailand",
    heroImage: "/site-images/singapore.jpg",
    duration: 6,
    nights: 5,
    budgetFrom: 65000,
    tags: ["Beach", "Culture", "Nightlife"],
    bestMonths: [11, 12, 1, 2, 3],
    suitableFor: ["Couples", "Friends", "Solo"],
    travelStyle: ["Leisure", "Adventure", "Culture"],
    status: "published",
    seoTitle: "Thailand Highlights — 6 Days 5 Nights | Adventourist",
    seoDescription: "Bangkok temples, Chiang Mai night markets, and Phuket beaches — the classic Thailand circuit done right.",
    overview: "Thailand offers something for everyone — ancient temples, frenetic street markets, world-class beaches, and food that haunts your dreams. This 6-day route hits the essential circuit: Bangkok's golden spires, Chiang Mai's misty mountains, and Phuket's turquoise bays.",
    highlights: [
      { icon: "🛕", label: "Grand Palace & Wat Pho", description: "Bangkok's sacred heart — golden stupas and reclining Buddha" },
      { icon: "🌺", label: "Chiang Mai Night Bazaar", description: "Silk, silverware, and street food under fairy lights" },
      { icon: "🏝️", label: "Phi Phi Islands Day Trip", description: "Emerald lagoons and limestone cliffs by longtail boat" },
      { icon: "🍜", label: "Thai Cooking Class", description: "Make pad thai and green curry with a Bangkok chef" },
    ],
    days: [],
    inclusions: ["5 nights accommodation", "Daily breakfast", "Airport transfers", "Phi Phi Islands day trip", "Bangkok city tour"],
    exclusions: ["Flights", "Thai visa (on arrival for Indians)", "Personal expenses", "Travel insurance"],
    faqs: [],
    hotels: [],
  },
];

export const MOCK_DESTINATIONS: Destination[] = [
  { id: "1", slug: "bali", name: "Bali", heroImage: "/bg-home-page.jpg", tagline: "Island of the Gods", region: "Indonesia", itineraryCount: 8, bestMonths: [4, 5, 6, 7, 8, 9], expertTip: "Skip the tourist-heavy areas of Kuta and base yourself in Ubud or Canggu for a more authentic experience. Ask us about hidden waterfall hikes and family-run warungs.", expertName: "Minal Shah", experiences: ["Food", "Culture", "Adventure", "Wellness", "Nature"] },
  { id: "2", slug: "leh-ladakh", name: "Leh Ladakh", heroImage: "/site-images/search-images-8.jpg", tagline: "Where Sky Meets Earth", region: "India", itineraryCount: 6, bestMonths: [6, 7, 8, 9], expertTip: "Always arrive a day early and do nothing on Day 1. Acclimatisation is non-negotiable at this altitude. Drink water, avoid alcohol, sleep early.", expertName: "Rahul Desai", experiences: ["Adventure", "Nature", "Culture", "Wellness"] },
  { id: "3", slug: "thailand", name: "Thailand", heroImage: "/site-images/singapore.jpg", tagline: "Land of Smiles", region: "Southeast Asia", itineraryCount: 5, bestMonths: [11, 12, 1, 2, 3], expertTip: "Visit Chiang Mai in November for the Yi Peng lantern festival — it's one of the most magical experiences in all of Asia.", expertName: "Priya Nair", experiences: ["Food", "Culture", "Beach", "Nightlife", "Adventure"] },
  { id: "4", slug: "sri-lanka", name: "Sri Lanka", heroImage: "/site-images/malaysia.jpg", tagline: "The Pearl of the Indian Ocean", region: "South Asia", itineraryCount: 4, bestMonths: [12, 1, 2, 3, 4], expertTip: "Don't just do the coast — the hill country around Ella and Nuwara Eliya is spectacular. The train ride from Kandy to Ella is one of the world's great train journeys.", expertName: "Aditya Kumar", experiences: ["Culture", "Nature", "Wildlife", "Beach", "Adventure"] },
  { id: "5", slug: "singapore", name: "Singapore", heroImage: "/site-images/singapore.jpg", tagline: "Lion City", region: "Southeast Asia", itineraryCount: 3, bestMonths: [2, 3, 4, 10, 11], expertTip: "Singapore is expensive to eat at restaurants — but the hawker centres are world-class and cost a fraction. Maxwell Food Centre and Lau Pa Sat are our favourites.", expertName: "Minal Shah", experiences: ["Food", "City", "Shopping", "Culture", "Nature"] },
  { id: "6", slug: "seychelles", name: "Seychelles", heroImage: "/site-images/dubai.jpg", tagline: "Paradise Redefined", region: "Indian Ocean", itineraryCount: 3, bestMonths: [4, 5, 10, 11], expertTip: "April and October (shoulder seasons) offer the best weather with fewer tourists and lower prices. Avoid December–January which is peak season with rain on Mahé.", expertName: "Priya Nair", experiences: ["Beach", "Luxury", "Wellness", "Nature", "Adventure"] },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  { id: "1", name: "Lata Valera", destination: "Thailand", rating: 5, text: "Exceptional experience with Adventourist Travel Co. Everything was managed really well. From hotels to activities — all seamless. I highly recommend them if you're planning any vacation.", avatar: "LV" },
  { id: "2", name: "Joiston & Priya", destination: "Bali · Honeymoon", rating: 5, text: "Minal and the team are absolutely amazing. They were extremely patient, kind and attentive. From hotel bookings to planning, to making changes while in Bali — Adventourist were right by our side.", avatar: "JP" },
  { id: "3", name: "Pranit Jaiswal", destination: "Leh Ladakh", rating: 5, text: "The Ladakh trip was beyond expectations. Every detail was taken care of — permits, hotels in remote areas, the whole route was perfect. Will definitely book again.", avatar: "PJ" },
  { id: "4", name: "Aman Rana", destination: "Singapore & Malaysia", rating: 5, text: "Booked a family trip through Adventourist and it was one of the best decisions. The kids loved every bit of it. Zero stress, everything pre-arranged.", avatar: "AR" },
  { id: "5", name: "Neha Singhi", destination: "Seychelles", rating: 5, text: "Dream honeymoon made real. The resort selection was impeccable, activities were perfectly timed, and the team was always reachable. Could not have asked for more.", avatar: "NS" },
  { id: "6", name: "Amyn Ghadiali", destination: "Vietnam", rating: 5, text: "Travelled solo to Vietnam with an Adventourist itinerary. The local guides they arranged were fantastic. The food trail in Hanoi was a highlight I'll never forget.", avatar: "AG" },
];

export const MOCK_STORIES: TravelStory[] = [
  { slug: "leh-ladakh-bucket-list", category: "Adventure", title: "11 Reasons Why Leh Ladakh Should Be on Every Indian's Bucket List", excerpt: "From the surreal Pangong Lake to the ancient monasteries of Thiksey — Ladakh is not just a destination, it's a transformation.", image: "/site-images/search-images-8.jpg", readTime: "6 min read", href: "https://blog.adventourist.in", featured: true },
  { slug: "vietnam-street-food", category: "Food & Culture", title: "The Street Food Trail That Changed My Perspective on Vietnam", excerpt: "Bun cha in Hanoi, banh mi from a street cart, and the best pho I've ever had — in a city that woke up my senses.", image: "/site-images/malaysia.jpg", readTime: "4 min read", href: "https://blog.adventourist.in" },
  { slug: "bali-honeymoon-48-hours", category: "Honeymoon", title: "We Planned Our Bali Honeymoon in 48 Hours — Here's How", excerpt: "When we said yes on a Tuesday, we had no idea we'd be in Ubud by Friday. Adventourist made it possible.", image: "/bg-home-page.jpg", readTime: "5 min read", href: "https://blog.adventourist.in" },
  { slug: "seychelles-packing-list", category: "Travel Tips", title: "The Only Seychelles Packing List You'll Ever Need", excerpt: "Reef-safe sunscreen, a light sarong, and reef shoes. Everything else? Leave it at home.", image: "/site-images/dubai.jpg", readTime: "3 min read", href: "https://blog.adventourist.in" },
];

export const BUDGET_OPTIONS = [
  { label: "Under ₹30,000", value: "under-30k" },
  { label: "₹30,000 – ₹60,000", value: "30k-60k" },
  { label: "₹60,000 – ₹1,00,000", value: "60k-1l" },
  { label: "₹1,00,000+", value: "above-1l" },
];

export const GROUP_SIZE_OPTIONS = [
  "Solo (1)", "Couple (2)", "Small Group (3–5)", "Medium Group (6–10)", "Large Group (10+)",
];

export const DURATION_OPTIONS = [
  { label: "3–5 Days", value: "3-5" },
  { label: "6–8 Days", value: "6-8" },
  { label: "9–12 Days", value: "9-12" },
  { label: "13+ Days", value: "13plus" },
];

export const TRAVEL_STYLE_OPTIONS = [
  "Leisure", "Adventure", "Luxury", "Backpacking", "Family", "Honeymoon", "Solo", "Culture",
];
